services:
  tor-1:
    container_name: tor-1
    image: pickapp/tor-proxy:0.4.7.13
    environment:
      - IP_CHANGE_SECONDS=15
    ports:
      - 8800:8888
    restart: unless-stopped

  tor-2:
    container_name: tor-2
    image: pickapp/tor-proxy:0.4.7.13
    environment:
      - IP_CHANGE_SECONDS=15
    ports:
      - 8888:8888
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.4.0-bookworm
    command: redis-server --save 60 1 --loglevel notice
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  redis-volume:
